client:
  - changed-files:
      - any-glob-to-any-file: 'flutter_client/**'
server:
  - changed-files:
      - any-glob-to-any-file: 'server/**'
documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'
dependencies:
  - changed-files:
      - any-glob-to-any-file: '**/package*.json'
      - any-glob-to-any-file: '**/pubspec.yaml'
